$(document).ready(function(){
	
		//防止搜索栏直接点击
	$('#searchForm').submit( function(e){
										if($('#booksuggest').val()=="请输入订单号")
										return false;
									});

	 
	///////////////////////////////////////////////////
	$('#booksuggest').focus(function(){
					if($(this).val()=='请输入订单号')
					{
						$(this).val('').css('color','#333');
					}
									 }).blur(function(){
												if($(this).val()=='')
												{
													$(this).val('请输入订单号').css('color','#CCCCCC');
												}
									 });
	$('#searchForm').submit(function(){
		UserSearch();
		return false;
	});
	
	//模糊查询书名
	function UserSearch(){
	  	var resultsDiv = $('#resultsDiv');
		$.ajax({
		   type: "POST",
		   url: "findOrder.php",
		   data: "order="+$('#booksuggest').val(),
		   dataType: 'json',
		   success: function(msg){         
					if(msg.errors==0){//失败，输出信息
							resultsDiv.empty();
                                          $('<p>',{class:'notFound',html:'抱歉，未找到相应订单!'}).hide().appendTo(resultsDiv).fadeIn();
					}
					else {	//查询到信息
							resultsDiv.empty();//先清空
							var results = msg;
                            var pageContainer = $('<div>',{class:'pageContainer',html:'订单搜索结果如下:'});

								pageContainer.append(new result(results) + '');

							pageContainer.append('<div class="clear"></div>')
										 .hide().appendTo(resultsDiv)
										 .fadeIn('slow');
										 
										
										 
										 
					}
		   }
		});


	}

	function result(r){	
		// This is class definition. Object of this class are created for
		// each result. The markup is generated by the .toString() method.
		var arr = [];
				arr = [
					'<div class="webResult" rel='+r.OrderID+'>',
					'<h2>订单号：'+r.OrderID+'</h2>',
                                  '<table style="font-size:15px;padding:5px 0 0 15px;"><tr><td style="width:170px;"><ul style="list-style:none;"><li>下单用户：'+r.UserName+'</li><li>用户ID:'+r.CustomerID+'</li></ul></td>',
                                  '<td style="width:170px;"><ul style="list-style:none;"><li id="fre">订单状态：<span class="freezed">'+r.State+'</span></li><li>订单总额：￥'+r.Amount+'</li></ul></td>',
                                  '<td style="width:275px;"><ul style="list-style:none;"><li>下单时间：'+r.dt+'</li></ul></td>',
								   '<td style="width:100px;"><ul style="list-style:none;"><li id="confirm"><a class="button small blue">执行</a></li></ul></td></tr></table>',
					'</div>'
				];
		// The toString method.
		this.toString = function(){
			return arr.join('');
		}
	}
	
	
});
