$(document).ready(function(){
	
		//防止搜索栏直接点击
	$('#searchForm').submit( function(e){
										if($('#booksuggest').val()=="请输入用户名")
										return false;
									});

	 
	///////////////////////////////////////////////////
	$('#booksuggest').focus(function(){
					if($(this).val()=='请输入用户名')
					{
						$(this).val('').css('color','#333');
					}
									 }).blur(function(){
												if($(this).val()=='')
												{
													$(this).val('请输入用户名').css('color','#CCCCCC');
												}
									 });
	$('#searchForm').submit(function(){
		UserSearch();
		return false;
	});
	
	//模糊查询用户
	function UserSearch(){
	  	var resultsDiv = $('#resultsDiv');
		$.ajax({
		   type: "POST",
		   url: "findUser.php",
		   data: "user="+$('#booksuggest').val(),
		   dataType: 'json',
		   success: function(msg){         
					if(msg.errors==0){//失败，输出信息
							resultsDiv.empty();
                                          $('<p>',{class:'notFound',html:'抱歉，未找到相应用户!'}).hide().appendTo(resultsDiv).fadeIn();
					}
					else {	//查询到信息
							resultsDiv.empty();//先清空
							var results = msg;
                            var pageContainer = $('<div>',{class:'pageContainer',html:'搜索结果如下，共'+results.length+'位:'});
							for(var i=0;i<results.length;i++){
								pageContainer.append(new result(results[i]) + '');
							}
							pageContainer.append('<div class="clear"></div>')
										 .hide().appendTo(resultsDiv)
										 .fadeIn('slow');
										 
											var style;									 
										 	var btnclass;
										 	var title;
											var message;
											var flag;
											var fremsg;
											var a;
											$('li#confirm a').click(function(){
												var btn=$(this);
												if($(this).html()=="账号冻结")
												{
													title="账号冻结";		
													message="您将要冻结此用户<br />请确认";
													flag=1;
													fremsg="账号已冻结";
													a="账号解冻";
													style='freezed';
													btnclass='button small green rounded';

												}
												else
												{
													title="账号解冻";		
													message="您将要解冻此用户<br />请确认";
													flag=0;
													fremsg="账号正常";
													a="账号冻结";
													style='unfreezed';
													btnclass='button small orange';
												}
												var elem = $(this).closest('.webResult');
												var uid=elem.attr('rel');
												$.confirm({
													'title'		: title,
													'message'	: message,
													'buttons'	: {
														'确定'	: {
															'class'	: 'button green medium',
															'action': function(){
																
																$.ajax({
																	type: "POST",
																	url: "freeze.php",
																	data: "uid="+uid+"&flag="+flag,
																	success: function(){
																			btn.html(a).removeClass().addClass(btnclass);
															elem.find('#fre').html(fremsg).removeClass().addClass(style);
																	}
																	   });
															}
														},
														'取消'	: {
															'class'	: 'button gray medium',
															'action': function(){}	
														}
													}
												});
											});

										 
										 
					}
		   }
		});


	}

	function result(r){	
		// This is class definition. Object of this class are created for
		// each result. The markup is generated by the .toString() method.
                var freeze;
				var style;
				var btnclass;
				if(r.Freeze==1)
                {
					r.Freeze="账号已冻结";
					freeze='账号解冻';
					style='class="freezed"';
					btnclass='class="button small green rounded"';
				}
                else
                {
					r.Freeze="账号正常";
					freeze='账号冻结';
					style='class="unfreezed"';
					btnclass='class="button small orange"';
				}
		var arr = [];
				arr = [
					'<div class="webResult" rel='+r.CustomerID+'>',
					'<h2>'+r.UserName+'</h2>',
                                  '<table style="font-size:15px;padding:5px 0 0 15px;"><tr><td style="width:110px;"><img src="../bInfo/images/'+r.Avatar+'" width="50" height="50"  alt="加载中" border="0"/></td>',
                                  '<td style="width:110px;"><ul style="list-style:none;"><li style="font-weight:bold;">ID:'+r.CustomerID+'</li><li '+style+' id="fre">'+r.Freeze+'</li></ul></td>',
                                  '<td style="width:275px;"><ul style="list-style:none;"><li>'+r.gender+'</li><li>'+r.province+'-'+r.city+'</li><li>最近登录时间：'+r.lasttime+'</li></ul></td>',
								   '<td style="width:100px;"><ul style="list-style:none;"><li id="confirm"><a '+btnclass+'>'+freeze+'</a></li></ul></td></tr></table>',
					'</div>'
				];
		// The toString method.
		this.toString = function(){
			return arr.join('');
		}
	}
	
	
});
