$(document).ready(function(){
	
		//防止搜索栏直接点击
	$('#searchForm').submit( function(e){
										if($('#booksuggest').val()=="请输入书名")
										return false;
									});

	 
	///////////////////////////////////////////////////
	//从主页传来的书名
	if($('#hiddenbn').val()!="")
	{
		$('#booksuggest').val($('#hiddenbn').val());
		ZHSearch();
	}
	else if($('#hiddenca').val()!="")	//从主页传来的类别
	{
		ZHSearchCa();
	}
	else	//直接在search.php,无任何get变量
		 $('#loading').fadeOut();
		 
	$('#searchForm').submit(function(){
		$('#loading').fadeIn();								 
		ZHSearch();
		return false;
	});
	//模糊查询书名
	function ZHSearch(){
	  	var resultsDiv = $('#resultsDiv');
		$.ajax({
		   type: "POST",
		   url: "findBList.php",
		   data: "book="+$('#booksuggest').val(),
		   dataType: 'json',
		   success: function(msg){   
		   			$('#loading').fadeOut(200);
					if(msg.errors==0){//失败，输出信息
							resultsDiv.empty();
                                          $('<p>',{class:'notFound',html:'抱歉，未找到相关书籍!'}).hide().appendTo(resultsDiv).fadeIn();
					}
					else {	//查询到信息
							resultsDiv.empty();//先清空
							var results = msg;
                            var pageContainer = $('<div>',{class:'pageContainer',html:'搜索结果如下，共'+results.length+'本:'});
							for(var i=0;i<results.length;i++){
								pageContainer.append(new result(results[i]) + '');
							}
							pageContainer.append('<div class="clear"></div>')
										 .hide().appendTo(resultsDiv)
										 .fadeIn('slow');
					}
		   }
		});


	}
		//根据类别查询书籍
		function ZHSearchCa(){
	  	var resultsDiv = $('#resultsDiv');
		$.ajax({
		   type: "POST",
		   url: "findBListCa.php",
		   data: "category="+$('#hiddenca').val(),
		   dataType: 'json',
		   success: function(msg){ 
		   		   			$('#loading').fadeOut(200);
             				if(msg.errors==0){//失败，输出信息
							resultsDiv.empty();
                                          $('<p>',{class:'notFound',html:'抱歉，未找到相关书籍!'}).hide().appendTo(resultsDiv).fadeIn();
					}
					else {	//查询到信息
							resultsDiv.empty();//先清空
							var results = msg;
                            var pageContainer = $('<div>',{class:'pageContainer',html:'['+$('#hiddenca').val()+']搜索结果如下，共'+results.length+'本:'});
							for(var i=0;i<results.length;i++){
								pageContainer.append(new result(results[i]) + '');
							}
							pageContainer.append('<div class="clear"></div>')
										 .hide().appendTo(resultsDiv)
										 .fadeIn('slow');
					}
		   }
		});
	}

	function result(r){	
		// This is class definition. Object of this class are created for
		// each result. The markup is generated by the .toString() method.
                if(r.Stock==1)
                r.Stock="现在有货";
                else
                r.Stock="暂时没货";
		var arr = [];
				arr = [
					'<div class="webResult">',
					'<h2><a href="../bInfo/index.php?bid='+r.BookID+'&bn='+encodeURIComponent (r.Bname)+'" target="_blank">'+r.Bname+'</a></h2>',
                                  '<table style="font-size:15px;padding:5px 0 0 15px;"><tr><td style="width:110px;"><a href="../bInfo/index.php?bid='+r.BookID+'&bn='+encodeURIComponent (r.Bname)+'" target="_blank" style="border:0;"><img src="../page1/img/'+r.imgName+'" width="80" height="100" id="bann"  alt="加载中" border="0"/></a></td>',
                                  '<td style="width:110px;"><ul style="list-style:none;"><li style="font-weight:bold;">￥'+r.SalePrice+'</li><li style="font-weight:bold;color:#990000;">'+r.Stock+'</li></ul></td>',
                                  '<td style="width:375px;"><ul style="list-style:none;"><li>作者：'+r.Author+'</li><li>类别：'+r.Category+'</li><li>出版社：'+r.Publisher+'</li></ul></td></tr></table>',
					'</div>'
				];
		// The toString method.
		this.toString = function(){
			return arr.join('');
		}
	}
	
	
});
